### ISSUE TITLE
Sort app list alphabetically

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode-spring-boot-dashboard#17]
Not sure how they are sorted in the view. It seems somewhat random to me, maybe it just depends on the hashing order in the Map. Should probably at least sort them explicitly in some logical fashion, like, alphabetic based on the name.

**Comment by Eskibear** [comment]
Alphabetic would not be the best choice I think. Suppose the user has multiple workspace root folders open, with multiple projects under each root folder, I'd rather to see these projects in group instead of simply in alphabetic order. 

e.g. If folder structure of workspace looks like
```
- Root folder X
| -- A1
| -- B1
| -- C1
- Root folder Y
| -- A2
| -- B2
| -- C2
```

Alphabetic view:
```
A1
A2
B1
B2
C1
C2
```

An example of grouped view:
```
A1
B1
C1
A2
B2
C2
```

Grouping introduces complexity, I think alphabetic is also acceptable for the first step, at least far better than random.

**Comment by kdvolder** [comment]
I'm open to other sortings. The current one however seems random, even just alphabetic sorting is better than that. I propose we go for alphabetic now, because:

a) it is trivial to implement
b) it is a clear improvement over the current implementation.

Then in the future it can be replaced with something better.

**Comment by Eskibear** [comment]
app list sorted alphabetically. https://github.com/Microsoft/vscode-spring-boot-dashboard/commit/9aa856f0e56d5b044aa1428705e14a9c3f757242
