### ISSUE TITLE
Open the project in web browser from the boot dashboard explorer 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/vscode-spring-boot-dashboard#6]

**Comment by Eskibear** [comment]
Open a link in browser can be easily implemented using package `opn`. But first we need to know the **PORT** that the app is listening.

**Comment by kdvolder** [comment]
This is (one place) where we need JMX to discover information about the app, i.e. what port it is listening on. We've got some Java code for doing this in STS / spring-ide. 

I can attempt to write something in typescript using the JMX library that we've tried out briefly.

It would be easiest for me to do that in the toy git repo I started already for experimenting with the library here: https://github.com/kdvolder/node-jmx-experiment

So I'll start there and post a update when I have something working there.

**Comment by kdvolder** [comment]
Hmm okay. The comment by @Eskibear here: https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/8#issuecomment-416105900

That doesn't really leave us with a practical way that we can determine server port unless...

I don't like this, but when a boot app starts it typically will log some message what port its running on. I really don't like this because the message format is not guaranteed, and, depending on the how a user configures the app's logging... may even not be there at all.

But if all we want is to detect the port that app is running on, examining its output and looking for that log message, maybe something to consider as an alternative to using JMX.

**Comment by kdvolder** [comment]
With the caveat whether we want to use this JMX library at all... I have updated my 'jmx-experiment' repo to get the port information from a running spring-boot app in this commit:

https://github.com/kdvolder/node-jmx-experiment/commit/f7a2a85db0a500cabc3b896e0df04057fbd85014

Not really sure how to proceed further right now. I think we first need to come to some kind of conclusion on whether or not we are going to use this library (with its native dependency).

BTW: For an example on what the output of a typical boot app looks like when it logs its port info is this:

```
2018-08-27 13:50:54.493  INFO 16982 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
```

Caveat. This is a 'typical' message but it could be different or absent. For example, the embedded server might not be tomcat but netty. Or user could configure there app to disable info messages etc.

**Comment by kdvolder** [comment]
@Eskibear @Matthew-Dong I'd like to hear what you think about the JMX library concundrum and how you think we should proceeed with this issue. Thanks.

**Comment by kdvolder** [comment]
Question, does either of you have some idea how feasible/hard it would be for spring-boot-dash extension to observe the launched process's output? I imagine it would be fairly straightforward if we were launching the process ourselves, but now that we are delegating process launch to the Java debugger, maybe that makes things a little more difficult?

**Comment by Eskibear** [comment]
> but now that we are delegating process launch to the Java debugger, maybe that makes things a little more difficult?

Not feasible so far. VS Code retrieves `output` event sent from the debug adapter, and render the content in the Debug Console.  There is an API to handle **CustomEvent**,  but `output` event is not a "custom" event.
```typescript
/**
 * An [event](#Event) which fires when a custom DAP event is received from the [debug session](#DebugSession).
 */
export const onDidReceiveDebugSessionCustomEvent: Event<DebugSessionCustomEvent>;
```

> I imagine it would be fairly straightforward if we were launching the process ourselves

Exactly. But I prefer to delegate it to the Java debugger for consistency, it provides more benefits as we discussed before. On the other hand, I don't think parsing stdout is a good way to know the port as your mentioned above:
>  _"This is a 'typical' message but it could be different or absent. For example, the embedded server might not be tomcat but netty. Or user could configure there app to disable info messages etc."_

And we also need to know more information besides the port. For me, JMX is still the best choice if possible.

**Comment by Eskibear** [comment]
BTW, I notice the Spring Boot Tools extension supports [quick access for running apps](https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-spring-boot#quick-access-for-running-apps) .  Can we leverage it here?

**Comment by kdvolder** [comment]
> Can we leverage it here?

Maybe, *if* we make some changes in "Spring Boot Tools extension" to expose some functionality via a command. At the moment, not possible without changes.

One problem/complication is that the spring-boot-tools extension directly scrapes local JVM processes, regardless of who started them. It dynamically enables JMX. In sense that is all good, as it means there's no need to add extra system properties upon app launch. 

On the other hand, this makes it difficult to know which process actually corresponds to a given project. So yes, it can give you a bunch of links, like you see in the screenshot, but it doesn't really know which link belongs to a specific project.

**Comment by Eskibear** [comment]
> "Spring Boot Tools extension" to expose some functionality via a command. 

Before it exposes related functionality (not sure whether it will), I have some naive ideas. Current the biggest problem with the JMX solution is that _node-jmx depends on native modules_. So why don't we simply implements the functionality in Java? I suppose there must be JMX related Java packages, and just like what "Debugger for Java" and "Spring Boot Tools extension" do, we can also use "java.execute.workspaceCommand" provided by the language server to execute the our own Java code (see https://github.com/redhat-developer/vscode-java/pull/292).

If it is possible to retrieve info of a spring-boot process via some Java JMX libs, then I think following workflow should have a good experience. 
1. It appends the required vmArgs(to enable JMX feature) to the DebugConfiguration when user clicks start/debug, 
2. await following command, to get the info we need. 
```typescript
vscode.commands.executeCommand("java.execute.workspaceCommand", 
    "the command to retrieve info",
    app.jmxUrl
)
```

What do you think?

**Comment by kdvolder** [comment]
> So why don't we simply implements the functionality in Java?

Sure, but that means we either have to 

a) create another Java process somehow and 'talk to it'.
b) piggyback onto a Java process that's already there and where we can contribute our code so that's like adding some code `Pivotal.vscode-spring-boot` or `redhat.java`.

So implementing this 'in Java' is possible (and one possible way to do this is by placing watever functionality we need into Pivotal.vscode-spring-boot', since its implemented as a Java language server and so it can implement / contribute commands to vscode).

To help our decision... How much of problem do you think it really is it that node-jmx requires native libraries? I mean it says this is 'not recommended'. But does that mean we really shouldn't do it at all? Or is it something we be able to get away with anyhow? I.e. I'm looking for a bit of a sense of how much of packaging / testing / etc. nightmare it might be.

**Comment by Eskibear** [comment]
Let me take [vscode-arduino](https://github.com/Microsoft/vscode-arduino) as an example. As far as I know, it leads to following work items:

#### First time dev work
* For a node.js runtime, 5 native modules ([x86, x64] * [Windows, Linux] + [MacOSX x64]) should be built. 
* Add extra logic to load correct native modules. E.g. https://github.com/Microsoft/vscode-arduino/blob/master/vendor/node-usb-native/lib/native_loader.js

#### Maintaining work
* Once VS Code upgrade Electron/Node with breaking changes, it requires to build 5 new modules and add them into the package. Otherwise it blocks users who just upgrade VSCode to the latest version. 

I've talked with a maintainer of vscode-arduino, 
* He created a bot monitoring the version of VS Code, and send himself a tweet if there's a breaking change. https://github.com/sneezry/vscode-version-watcher
* Once there's a new version, he has a repo https://github.com/Sneezry/serialport.node to with kinds of CI jobs to build native modules for different platforms. 

#### My concern
* The size of the extension will be larger (more and more built native modules are put inside) as time goes on. But it's not a blocking issue. 
* For vscode-arduino, it's using a native module directly, so they are able to somehow write the [native loader](https://github.com/Microsoft/vscode-arduino/blob/master/vendor/node-usb-native/lib/native_loader.js). In our extension, we depends on [node-jmx](https://github.com/zuazo/node-jmx), and node-jmx depends on the native module [node-java](https://github.com/joeferner/node-java). That means we have to fork node-jmx, and add something like native_loader there. Correct me if I'm wrong. 

Back to the comparison between Java and node-jmx, I'm not 100% sure but I imagine node-jmx eventually executes some Java code to "talk to" the boot app. (because I see it requires Java 6 or higher) And I happened to find some result when searching "jmx" in STS4 repo, e.g. 
```
headless-services/commons/commons-boot-app-cli/src/main/java/org/springframework/ide/vscode/commons/boot/app/cli/LocalSpringBootApp.java
```
And the path contains "vscode/common" so I suppose there's already related code for the JMX feature. That's why I had the idea of implementing it directly in Java.

**Comment by kdvolder** [comment]
Packaging node-jmx and its native libs seems to much hassles from what you describe.

So I think one way or another we are going to have to implement something in Java. 

I see two possibe approaches:

a) keep it within vscode-spring-boot-dashboard. This means, adding some Java code and some build-logic for it. And some code for launching it from typescript. We'll have communicate with that process somehow too. Perhaps we just passing a payload on system in on launch and read the result from system out. The process could exit after its answered the JMX request, or it could stay up. (The former is probably simpler to manage but pays a high overhead of launching JVM on top of making JMX connection each time we need make a JMX request.

b) place some code into vscode-spring-boot extension. Advantage: vscode-spring-boot already does JMX things, so it has most of the machinery already in place. Drawback: creates more tight coupling between our two plugins (but we already have some strong coupling anyway because of the dependency to obtain classpath data).

Not sure which approach is best. Ultimately, maybe it doesn't matter much and we just have to pick one approach and go with it.

BTW: Implementing some 'get info from JMX' thing in Java isn't terribly hard. I think rather the complexity will be in the things we have to do to building, package and running the Java code from typescript.  

Thoughts? Do you have a preference for option a) or b). Myself, I don't have a strong preference as both have some advanatges/disadvantages but I think I'm leaning sligthty towards option a). I.e. avoid the extra coupling even though it means dealing with the cost of starting an extra process and doing a bit more scaffloding on the vscode-spring-boot-dashboar side to support running some java code.

**Comment by kdvolder** [comment]
BTW: I didn't mean to box this as a 'either/or' choice, perhaps you had a different idea than option a) or b) above, if so, that be interesting to hear about too... of course!

**Comment by Eskibear** [comment]
`a)` looks better for me.

**Comment by Eskibear** [comment]
@kdvolder I tried a little bit on scaffolding work, forming a PR #26 . Tycho is not friendly to me, but anyway I manage to get a minimum viable one (no much consideration in design, convention, etc.). If we agree on option a), then please take a look the PR and see if it's acceptable for you to work on?

**Comment by kdvolder** [comment]
@Eskibear If we are going with option a) we don't have make our 'little Java process' an osgi bundle (i.e tycho)

However, looking at your PR, I think it is doing something that is neither option a) or b). Well... not exactly as I understood them anyways. I think your PR uses the redhat java as a host to execute the Java code. And yes, that means osgi etc. since this is a requirement to contribute code to them via their extension mechanism. That makes sense if you want to do answer requests that, practically speaking only the redhat.java extension can answer (e.g. determine a project's classpath, find errors in the project, discover which projects redhat.java is managing etc.). Arguably, it makes a lot less sense to go that route if the functionality isn't really dependent on redhat.java. (Effecitvely, you are just using it as a 'shell' to execute your Java code in its process). 

So here's the options I see now, with you PR added to the list as option c)

a) develop a small Java process that we build and launch ourselves from vscode-spring-boot-dashboard. We are fully responsible for managing the process's lifecycle and for creating a 'communication channel' with the process (e.g. sysin + sysout) and exit after each request.
b) contribute our Java code via a PR to vscode-spring-boot. Communincation is via executing vscode command registered by vscode-spring-boot PR.
c) contribute our Java code via redhat.java extension. Use its extension mechanism (i.e. build an osgi bundle that is supposed to link with its 'mini eclipse' OSGI environment at runtime, add entry to our package.json to tell redhat.java to load it). Communication is via worspace/executeCommand command registered by redhat.java extension.

Option a) is the one that is the most 'self contained' and gives us most control over the mechanics. But it means we have to do a lot of things ourselves. For example, finding the 'java' executable on the user's system. Luckily, we already have a node package for that somewhere: https://www.npmjs.com/package/@pivotal-tools/jvm-launch-utils

Personally I don't like option c) very much because it gives us very little control over the environment in which our  Java code gets executed (it is whatever target platform the redhat.java uses). Also it forces us to deal with all the complexities of osgi, but without having real control over target platform we are being linked with. That being said, our requirements for dependencies is probably minimal or even zero (JMX libraries are built-in with the JRE). So maybe this is not really a problem.

Okay... so I'll try and do something similar to your PR to exemplify option a) and maybe we can compare between your PR for option c) and decide then what to do.

**Comment by Eskibear** [comment]
Thanks for the articulation, and now I know what I thought was not the option a) you mentioned. I myself also dislike the osgi things, which seems not so friendly with not-so-experienced Java developer like me. I just had a quick look at the comment above, I suppose option a) would be much more “little” especially with the existing jvmutils package. 
It’s midnight here and I just want to clarify I’m not sticking with option c) . I’ll think more about it tomorrow when my mind is clearer.

**Comment by kdvolder** [comment]
>  I suppose option a) would be much more “little” especially with the existing jvmutils package.

Well, not really. It depends on how you look at it. In terms of runtime cost, I think option c) has a definite advantage because essentially you are executing your code on a JVM process that is already running anyway (the jdt language server). So it doesn't incur the cost of launching an extra process.

It's also has the advantage that redhat folks already created a rudimentary 'communication' mechanism. I.e. with all the correct entries in package.json the redhat.java extension routes 'vscode.java.executeWorkspaceCommand' requests to be executed by our Java code. This lets our code call on the java code and get a result back (as you did in your PR).

The biggest drawback to me is that you have no control over that process. It is basically a little 'mini eclipse' which contains osgi bundles exactly as the target platform for redhat.java defines.

**Comment by Eskibear** [comment]
Let's consider the possible use cases and workflow in the future. I'm using "TS" & "JAVA" to distinguish the code running in different places. 

#### Start/Debug
1. TS starts (with/without debugging) a boot app with JMX enabled, change its status immediately to "launching"(we don't have yet).  Now TS knows the jmxuri.
2. TS asks JAVA to talk to the boot app, wants to know the status (still "launching" / "running" / somehow "inactive" ).  Here if JAVA exit after each request, TS should have to keep polling, and it looks expensive to repeatedly create java process.
3. TS wants to render properties (roughly mentioned in #8 ) of a boot app, same as above, more requests are sent to JAVA. 
...

I don't see any drawbacks in your PR exemplifying option a), it look simple and easy to use. The main concern is the "little java process" would probably be called very often, so the process launching cost would matter. 
How do you think if we make it a "little java service", accepting request from stdin, giving response to stdout, utill we send it a customized "stop command"?

**Comment by kdvolder** [comment]
> How do you think if we make it a "little java service", accepting request from stdin, giving response to stdout, utill we send it a customized "stop command"?

If the cost of launching JVM process and creating JMX connectors repeatedly is too much (which I think is almost certain), then we will have to go that route.

I don't think it is very hard. But you'll need a bit more of a communication 'protocol' of some kind. The current code is very simple because the receiving process knows it only gets one request on system.in. The calling process knows it only gets one result on system out.

With a long lived process the protocol would be a little more complex because it needs to parse multiple request / response. So there will be more boilerplate around that. Also, depending on whether we'd need to support multiple concurrent requests, that would add more complexity again.

But I think we can just take things one step at a time. Start with the simplest thing first and add that complexity when the need arises.

We are in the middle of a milestone release at the moment, but I'll see if I can find some time today to implement a simple 'get port from JMX using this url' functionality today.

**Comment by kdvolder** [comment]
The PR was updated. It now is able to get port information. But only the part that fetches the info from jmx is working/implemented. 

Still missing:

- enable JMX and the spring boot admin bean. (requires adding system properties on launching app)
- find out what port JMX is enabled on for the app (depends on how it was launched, the port should be set on launching the app).

**Comment by Eskibear** [comment]
I've tried it out and it works. I think it's the right approach and we should go with it. 

For the setting of JMX port, I think of following alternatives:

i) For each launch, the extension generates a random port, constructs the required vmargs, start/debug with config from launch.json + vmargs. In this approach, vmargs is not saved into launch.json with the config, it's dynamically appended to the config before launch. So the jmxport is kept as an attribute in boot app when user start it. 
Advantage: Users don't have to know the vmargs and the jmxport, the extension pick a random and available port (I believe it's possible) for it. 


ii) The first time it generates the launch.json for a boot app, the extension pick a random port, construct vmargs into the config. In this approach, the jmxport is binded with the config itself, for each launch of the same app, it uses the same jmxport. 
Advantage: The jmx things are transparent to users, if users use <kbd>F5<kbd> to launch a boot app, the jmx things still work. 
Drawback: The jxmport has to be parsed from the launch.json.

For me I think i) is better.

**Comment by kdvolder** [comment]
I am also leaning towards i). But this requires that we are able to somehow intercept how java debug extension launches the app (so that we can modify launch parameters at the last moment, without actually making changes to the launch.json directly).

**Comment by Eskibear** [comment]
>  somehow intercept how java debug extension launches the app 

Yes, we can, and we are doing this way already. When we start a boot app without debugging, actually we append `noDebug: true` to the original one, without making changes to the launch.json. In the same way we can append vmargs.
```typescript
const ok: boolean = await vscode.debug.startDebugging(
    vscode.workspace.getWorkspaceFolder(vscode.Uri.parse(app.path)),   // <-- a workspace folder
    Object.assign({}, targetConfig, { noDebug: !debug })  // <-- a DebugConfiguration. 
);
```

**Comment by kdvolder** [comment]
See PR ^^. I think I implemented as @Eskibear proposed it should work. One thing I worry a little about is what would happen if a user also decided to enable JMX for whatever reason. I'm not really sure if / how we should handle this somehow. But as it is now, I'm not sure what will happen if the same or conflicting system properties are being set multiple times because we and the user are both trying to set them. So I left a TODO in the code about this.

**Comment by Eskibear** [comment]
Closing this one as I think the feature is done.
